"""Canonical fail-closed error registry for the coalition swarm."""
from __future__ import annotations
from dataclasses import dataclass
from enum import Enum

class Severity(str, Enum):
    BLOCKING = "BLOCKING"
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"

@dataclass(frozen=True)
class ErrorSpec:
    code: str
    severity: Severity
    rule: str

BLOCKERS = {
    "COLMENA_STATE_MISSING","COLMENA_STATE_INVALID","INVOCATION_MISSING","CONTRACT_MISSING",
    "METHOD_MISMATCH","SEED_MISMATCH","SOURCE_ANCHOR_MISSING","SOURCE_HASH_DECLARATION_MISMATCH",
    "PRIMARY_BINARY_NOT_REPOSITORY_PINNED","PRIMARY_HASH_MISMATCH","EVIDENCE_MISSING","EVIDENCE_STALE",
    "FUTURE_INFORMATION","DATA_CONTRADICTION","REPRODUCIBILITY_FAILURE","PARAMETER_DRIFT",
    "METHODOLOGY_DRIFT","UNSUPPORTED_INFERENCE","HIDDEN_IMPUTATION","COALITION_SEAT_SUMMATION",
    "PARTISAN_OPTIMIZATION","EXTERNAL_AUDIT_UNAVAILABLE","UNPERSISTED_CHECKPOINT",
    "MULTIPLE_NEXT_ACTIONS","CHAT_CONTEXT_DEPENDENCY","CERTIFICATION_WITH_OPEN_BLOCKER",
    "PRIMARY_RECONCILIATION","SEEC_PRODUCTION_EXECUTION","OOS_CALIBRATION","EXTERNAL_AUDIT",
    "ABSOLUTE_TIE","INVALID_VALID_VOTES","SEAT_CONSERVATION","UNVERSIONED_DATA",
    "INVENTED_TERRITORIALITY","MANUAL_RESULT_OVERRIDE","NONDETERMINISTIC_EXECUTION","CI_EVIDENCE_MISSING_FOR_CONTINUITY_COMMIT","PRIMARY_2023_MATRIX_MATERIALIZATION"
}
ERRORS = {code: ErrorSpec(code, Severity.BLOCKING, code) for code in BLOCKERS}
ERRORS.update({
    "DUPLICATE_WORK": ErrorSpec("DUPLICATE_WORK", Severity.ERROR, "Reuse already verified evidence."),
    "TOKEN_BUDGET_RISK": ErrorSpec("TOKEN_BUDGET_RISK", Severity.ERROR, "Persist a checkpoint before continuing.")
})

def is_blocking(code: str) -> bool:
    return code in ERRORS and ERRORS[code].severity is Severity.BLOCKING

def validate_code(code: str) -> None:
    if code not in ERRORS:
        raise ValueError(f"UNKNOWN_ERROR_CODE:{code}")
